### ISSUE TITLE
Run errors of example.py and example2.py

### ISSUE THREAD

**Issue by liuqi8827** [clvoloshin/COBS#16]
Hi,

1. When I run **python example.py**, the output showed:
{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 0: 0, 7: 1}
{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 0: 0, 7: 1}
{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 0: 0, 7: 1}
{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 0: 0, 7: 1}
{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 0: 0, 7: 1}

  0%|          | 0/10000 [00:00<?, ?it/s]
  0%|          | 0/10000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lq/COBS/example.py", line 91, in <module>
    main()
  File "/home/lq/COBS/example.py", line 81, in main
    results = runner.run()
  File "/home/lq/COBS/ope/experiment_tools/experiment.py", line 84, in run
    result = self.single_run(cfg)
  File "/home/lq/COBS/ope/experiment_tools/experiment.py", line 128, in single_run
    eval_data = rollout(env, pi_e, processor, absorbing_state, N=max(10000, cfg.num_traj), T=T, frameskip=frameskip, frameheight=frameheight, path=None, filename='tmp',)
  File "/home/lq/COBS/ope/utls/rollout.py", line 389, in rollout
    frames = [true_state]*frameheight
TypeError: can't multiply sequence by non-int of type 'NoneType'

2. When I run **python example2.py**, the output showed:

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:06<00:00, 1572.75it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1284.28it/s]
Traceback (most recent call last):
  File "example2.py", line 98, in <module>
    main()
  File "example2.py", line 89, in main
    results = runner.run()
  File "/home/lq/COBS/ope/experiment_tools/experiment.py", line 88, in run
    result = self.single_run(cfg)
  File "/home/lq/COBS/ope/experiment_tools/experiment.py", line 141, in single_run
    if cfg.to_regress_pi_b['to_regress']:
TypeError: 'bool' object is not subscriptable

Can you give me some suggestions?
Thanks a lot!

**Comment by clvoloshin** [comment]
These are configuration issues. The configuration was updated after example/example2 was made. I will update them so they work but my recommendation right now is to see example3/example4 and the tutorial.ipynb instead. You will see how to run example3/example4 in the __main__ function within the respective files. 

Example.py and Example3.py are essentially the same, so are Example2 and Example4.py. The only real difference is that the configuration is sitting in a file within /cfgs (for example3/4) rather than hardcoded in the file (example1/2).

**Comment by clvoloshin** [comment]
To make things less confusing, I deleted example/example2 and renamed example3/4. Please see README for how to run.

**Comment by liuqi8827** [comment]
Thanks for your quick reply. I can run example3.py, example4.py and tutorial.ipynb successfully.
