### ISSUE TITLE
use of propensity

### ISSUE THREAD

**Issue by LongchaoDa** [clvoloshin/COBS#19]
**Could the author explain the use and meaning of:**

target_propensity,
base_propensity ,
extra_propensity

**Comment by clvoloshin** [comment]
target is probability given by pi_e(a|s) (the evaluation policy). base is the probability given by pi_b(a|s) (the behavior policy). extra_propensity is a terminal probability

**Comment by LongchaoDa** [comment]
Thank you! 

I have another confusion, Do the x, and x_prime in the code mean the state_t and state_t+1 ? 
When I try to understand the value of the Data class, x seems hard to understand, what is the index in the array eg.'x': [[0], [1], [2], [3], [4]]?  and its relationship to 'x_prime': [[1], [2], [3], [4], [5]].  Is it the frame index?  And for the true history states, is it stored in the `Frames` list?

**Comment by clvoloshin** [comment]
x and x_prime are pointers to the index of the state; this is useful for space reasons. So if there's some array state = [a, b, c, d, e] then x = [[0], [1], [2]] corresponds to [[a], [b], [c]] and x_prime = [[1],[2],[3]] corresponds to [[b], [c], [d]].
